// Writes src/renderer/generated/katex.css: KaTeX's stylesheet with its
// woff2 fonts inlined as data URIs, so the same CSS serves the preview, the
// offscreen PNG/PDF window (a temp file with no fonts beside it) and a
// standalone HTML export. The woff and ttf fallbacks are dropped: every
// Chromium and every browser this can be opened in reads woff2. Run by
// postinstall and before start/make/test; the output is not committed.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'node_modules', 'katex', 'dist');
const outDir = path.join(root, 'src', 'renderer', 'generated');
const out = path.join(outDir, 'katex.css');

const css = fs.readFileSync(path.join(dist, 'katex.min.css'), 'utf8');
const inlined = css.replace(/src:([^;}]+)/g, (whole, sources) => {
  const woff2 = /url\((fonts\/[^)]+\.woff2)\)\s*format\("woff2"\)/.exec(sources);
  if (!woff2) return whole;
  const file = path.join(dist, woff2[1]);
  const data = fs.readFileSync(file).toString('base64');
  return `src:url(data:font/woff2;base64,${data}) format("woff2")`;
});

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(out, `/* Generated by scripts/katex-css.mjs; do not edit. */\n${inlined}`, 'utf8');
console.log(`${path.relative(root, out)}: ${(inlined.length / 1024).toFixed(0)} KB`);
